[build]
builder = "nixpacks"

[deploy]
restartPolicyType = "never"

# Web 进程：ASGI 应用（Bot Webhook + 管理面板由 asgi_app/main.py 提供）
[deploy.web]
command = "python3 main.py"
restartPolicyType = "on-failure"
checkTimeout = 300
healthcheckPath = "/health"
healthcheckTimeout = 30

# Worker 进程：定时任务调度器
[deploy.worker]
command = "python3 scheduler.py"
restartPolicyType = "on-failure"

[[deploy.hooks]]
stage = "post-deploy"
command = "python3 scripts/post_deploy_hook.py"

[environments.production]
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

[environments.production.variables]
RUN_MODE = "prod"
DEBUG = "false"
USE_WEBHOOK = "true"
BOT_TOKEN = "8405793737:AAF0K4I_cs19TL-ED8-SYag_GNHIT5gAGSk"
DEEPLINK_BOT_USERNAME = "baiduyuntestbot"

[environments.staging]

[environments.staging.variables]
RUN_MODE = "prod"
DEBUG = "true"
USE_WEBHOOK = "true"
WEB_BASE_PATH = "/admin"
